let autos = [  
  { 
      "id": 1, 
      "idusuario": 2, 
      "tipo": "Camioneta", 
      "marca": "Nissan", 
      "modelo": "Kicks", 
      "version": "Advance", 
      "anio": 2020, 
      "kilometros": 20000, 
      "transmision": "Automática", 
      "rodado": 17, 
      "potencia": 118, 
      "capacidad_carga": 350, 
      "traccion": "Delantera", 
      "color": "Rojo", 
      "precio": 300000, 
      "descripcion_adicional": "Único dueño, servicios de agencia, en excelente estado", 
      "fotos": [ 
        "https://www.nissan-cdn.net/content/dam/Nissan/ar/vehicles/thumbnails/cars/Kicks_23_Advance_Plus.jpg.ximg.l_12_m.smart.jpg", 
        "https://ejemplo.com/foto5.jpg", 
        "https://ejemplo.com/foto6.jpg" 
      ] 
    }, 
    { 
      "id": 2, 
      "idusuario": 3, 
      "tipo": "Auto", 
      "marca": "Ford", 
      "modelo": "Fiesta", 
      "version": "SE", 
      "anio": 2019, 
      "kilometros": 40000, 
      "transmision": "Automática", 
      "rodado": 15, 
      "potencia": 120, 
      "capacidad_carga": 300, 
      "traccion": "Delantera", 
      "color": "Azul", 
      "precio": 250000, 
      "descripcion_adicional": "Excelente estado, servicios de agencia, único dueño", 
      "fotos": [ 
        "https://autotest.com.ar/wp-content/uploads/2021/09/Ford-Fiesta-SE-Plus-cola.jpg", 
        "https://ejemplo.com/foto8.jpg", 
        "https://ejemplo.com/foto9.jpg" 
      ] 
    }, 
    { 
      "id": 3, 
      "idusuario": 1,
      "tipo": "Camioneta", 
      "marca": "Chevrolet", 
      "modelo": "Silverado", 
      "version": "LT", 
      "anio": 2020, 
      "kilometros": 5000, 
      "transmision": "Automática", 
      "rodado": 18, 
      "potencia": 355, 
      "capacidad_carga": 1000, 
      "traccion": "4x4", 
      "color": "Gris", 
      "precio": 700000, 
      "descripcion_adicional": "Prácticamente nueva, servicios de agencia, único dueño", 
      "fotos": [ 
        "https://www.chevrolet.com.uy/content/dam/chevrolet/south-america/uruguay/espanol/index/pick-ups/2021-silverado/01-images/galeria/exterior/chevrolet-silverado-camioneta-pick-up-exterior.jpg?imwidth=960", 
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": 4, 
      "idusuario": 3,
      "tipo": "Auto", 
      "marca": "Honda", 
      "modelo": "Civic", 
      "version": "Touring", 
      "anio": 2021, 
      "kilometros": 0, 
      "transmision": "Automática", 
      "rodado": 17, 
      "potencia": 174, 
      "capacidad_carga": 350, 
      "traccion": "Delantera", 
      "color": "Negro", 
      "precio": 450000, 
      "descripcion_adicional": "Nuevo modelo 2021 con sistema de sonido premium y asientos de piel", 
      "fotos": [ 
        "https://www.carpro.com/hubfs/2022-Honda-Civic-feature-carprousa.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": 5, 
      "idusuario": 2,
      "tipo": "Camioneta", 
      "marca": "Jeep", 
      "modelo": "Compass", 
      "version": "Limited", 
      "anio": 2020, 
      "kilometros": 15000, 
      "transmision": "Automática", 
      "rodado": 18, 
      "potencia": 180, 
      "capacidad_carga": 400, 
      "traccion": "4x4", 
      "color": "Blanco", 
      "precio": 550000, 
      "descripcion_adicional": "Servicios de agencia, en excelente estado", 
      "fotos": [ 
        "https://rosasautomotriz.com/wp-content/uploads/2022/04/Jee-Compass-Sport-2014-RosasAutomotriz16-730x535.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": 6, 
      "idusuario": 1,
      "tipo": "Auto", 
      "marca": "Mazda", 
      "modelo": "MX-5", 
      "version": "RF", 
      "anio": 2021, 
      "kilometros": 0, 
      "transmision": "Manual", 
      "rodado": 17, 
      "potencia": 181, 
      "capacidad_carga": 200, 
      "traccion": "Trasera", 
      "color": "Rojo", 
      "precio": 600000, 
      "descripcion_adicional": "Nuevo modelo 2021, descapotable, asientos deportivos de piel", 
      "fotos": [ 
        "https://img.remediosdigitales.com/0ce237/mazda-mx-5-na.-02/1366_2000.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": 7, 
      "idusuario": 3,
      "tipo": "Auto", 
      "marca": "Volkswagen", 
      "modelo": "Vento", 
      "version": "Highline", 
      "anio": 2018, 
      "kilometros": 60000, 
      "transmision": "Automática", 
      "rodado": 15, 
      "potencia": 110, 
      "capacidad_carga": 350, 
      "traccion": "Delantera", 
      "color": "Gris", 
      "precio": 200000, 
      "descripcion_adicional": "Único dueño, servicios de agencia, en buen estado", 
      "fotos": [ 
        "https://i0.wp.com/tiempomotor.com/wp-content/uploads/2019/06/Vento_Highline_Test_11.jpg?resize=960%2C720&ssl=1",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": 8, 
      "idusuario": 2,
      "tipo": "Camioneta", 
      "marca": "Renault", 
      "modelo": "Captur", 
      "version": "Zen", 
      "anio": 2019, 
      "kilometros": 35000, 
      "transmision": "Automática", 
      "rodado": 17, 
      "potencia": 118, 
      "capacidad_carga": 350, 
      "traccion": "Delantera", 
      "color": "Azul", 
      "precio": 280000, 
      "descripcion_adicional": "Servicios de agencia, en buen estado", 
      "fotos": [ 
        "https://http2.mlstatic.com/D_NQ_NP_638422-MLA69817374247_062023-O.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": 9, 
      "idusuario": 1,
      "tipo": "Camioneta", 
      "marca": "Ford", 
      "modelo": "Ranger", 
      "version": "XLT", 
      "anio": 2020, 
      "kilometros": 10000, 
      "transmision": "Automática", 
      "rodado": 18, 
      "potencia": 270, 
      "capacidad_carga": 1000, 
      "traccion": "4x4", 
      "color": "Negro", 
      "precio": 750000, 
      "descripcion_adicional": "Servicios de agencia, en excelente estado", 
      "fotos": [ 
        "https://www.deruedas.com.ar/images/autos/593/593662_1_im.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": 10, 
      "idusuario": 3,
      "tipo": "Auto", 
      "marca": "Chevrolet", 
      "modelo": "Cruze", 
      "version": "LT", 
      "anio": 2017, 
      "kilometros": 80000, 
      "transmision": "Automática", 
      "rodado": 16, 
      "potencia": 153, 
      "capacidad_carga": 350, 
      "traccion": "Delantera", 
      "color": "Gris", 
      "precio": 180000, 
      "descripcion_adicional": "Único dueño, en buen estado", 
      "fotos": [ 
        "https://tiendacars.com/media/2023/05/6054_23251_desktop.jpeg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": 11, 
      "idusuario": 2,
      "tipo": "Camioneta", 
      "marca": "Toyota", 
      "modelo": "Rav4", 
      "version": "XLE", 
      "anio": 2019, 
      "kilometros": 30000, 
      "transmision": "Automática", 
      "rodado": 17, 
      "potencia": 203, 
      "capacidad_carga": 400, 
      "traccion": "4x4", 
      "color": "Blanco", 
      "precio": 500000, 
      "descripcion_adicional": "Servicios de agencia, en excelente estado", 
      "fotos": [ 
        "https://http2.mlstatic.com/D_NQ_NP_683676-MLA70109527517_062023-O.webp",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
  },
  {
  "id": 12,
  "idusuario": 1,
  "tipo": "Auto",
  "marca": "Volkswagen",
  "modelo": "Arteon",
  "version": "R-Line",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 20,
  "potencia": 268,
  "capacidad_carga": 400,
  "traccion": "4x4",
  "color": "Blanco",
  "precio": 800000,
  "descripcion_adicional": "Nuevo modelo 2021 con sistema de cámara 360 y asientos de cuero Nappa",
  "fotos": [
    "https://images.carexpert.com.au/resize/3000/-/app/uploads/2022/02/2022-Volkswagen-Arteon-206TSI-R-Line-Liftback-HERO.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyQ6n9u8qaaxAPsIezls96pLdYfWKKD1QVFNCo9IURRX_B7KQa25b81wPToyAe1XgjjrQ&usqp=CAU",
    "https://vw.plichta.com.pl/wp-content/uploads/otomoto-sync/464747/b2dcba9f6ee86625d66d64adc9dac48f.jpg"
  ]
  }, {
  "id": 13,
  "idusuario": 2,
  "tipo": "Camioneta",
  "marca": "Volkswagen",
  "modelo": "Tiguan",
  "version": "R-Line",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 20,
  "potencia": 184,
  "capacidad_carga": 500,
  "traccion": "4x4",
  "color": "Azul",
  "precio": 700000,
  "descripcion_adicional": "Nuevo modelo 2021 con sistema de sonido Fender y techo panorámico corredizo",
  "fotos": [
    "https://fncdn.blob.core.windows.net/web-clean/1/root/arteon.jpg",
    "https://vw.plichta.com.pl/wp-content/uploads/otomoto-sync/464747/b2dcba9f6ee86625d66d64adc9dac48f.jpg",
    "https://www.autoscout24.de/cms-content-assets/4IsmvtZbVx6Jyk0VShBcf1-e802e145588bc66774cf53e10a5fe640-vw-arteon-back-1100.jpeg"
  ]
},{"id": 14,
  "idusuario": 3,
  "tipo": "Auto",
  "marca": "Volkswagen",
  "modelo": "Passat",
  "version": "R-Line",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 19,
  "potencia": 276,
  "capacidad_carga": 400,
  "traccion": "Delantera",
  "color": "Gris",
  "precio": 600000,
  "descripcion_adicional": "Nuevo modelo 2021 con sistema de asistencia de frenado de emergencia y control de crucero adaptativo",
  "fotos": [
    "https://http2.mlstatic.com/D_NQ_NP_999509-MLA54657779141_032023-O.webp",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
  },
  {
  "id": 15,
  "idusuario": 3,
  "tipo": "Auto",
  "marca": "Volkswagen",
  "modelo": "Golf",
  "version": "GTI",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 18,
  "potencia": 241,
  "capacidad_carga": 400,
  "traccion": "Delantera",
  "color": "Negro",
  "precio": 500000,
  "descripcion_adicional": "Nuevo modelo 2021 con techo corredizo panorámico y sistema de navegación",
  "fotos": [
    "https://cdn.motor1.com/images/mgl/B3Pme/s1/llego-a-la-argentina-el-ultimo-embarque-de-vw-golf-gti.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": 16,
  "idusuario": 2,
  "tipo": "Auto",
  "marca": "Volkswagen",
  "modelo": "Jetta",
  "version": "GLI",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 18,
  "potencia": 228,
  "capacidad_carga": 400,
  "traccion": "Delantera",
  "color": "Rojo",
  "precio": 450000,
  "descripcion_adicional": "Nuevo modelo 2021 con sistema de sonido premium y asientos deportivos",
  "fotos": [
    "https://hips.hearstapps.com/hmg-prod/images/2022-volkswagen-jetta-gli-autobahn-103-edit-1645827739.jpg?crop=0.622xw:0.699xh;0.129xw,0.301xh&resize=640:*",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": 17,
  "idusuario": 1,
  "tipo": "Auto",
  "marca": "Citroen",
  "modelo": "C3",
  "version": "Feel",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Manual",
  "rodado": 16,
  "potencia": 82,
  "capacidad_carga": 300,
  "traccion": "Delantera",
  "color": "Rojo",
  "precio": 300000,
  "descripcion_adicional": "Nuevo modelo 2021 con pantalla táctil de 7 pulgadas y cámara de reversa",
  "fotos": [
    "https://resizer.glanacion.com/resizer/VF2xQu7-PgIE6h3S9-4U-RSluTY=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/4FYT7ABYINEGZGUA5TGGBXWBGA.jpeg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": 18,
  "idusuario": 2,
  "tipo": "Camioneta",
  "marca": "Citroen",
  "modelo": "C4 Cactus",
  "version": "Feel",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 17,
  "potencia": 118,
  "capacidad_carga": 500,
  "traccion": "Delantera",
  "color": "Blanco",
  "precio": 400000,
  "descripcion_adicional": "Incluye techo panorámico y sistema de navegación GPS",
  "fotos": [
    "https://automobileslyon.com.ar/wp-content/uploads/2020/12/3-1-898x558.jpg?x10793",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": 19,
  "idusuario": 4,
  "tipo": "Camioneta",
  "marca": "Citroen",
  "modelo": "Berlingo",
  "version": "Feel",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Manual",
  "rodado": 15,
  "potencia": 110,
  "capacidad_carga": 800,
  "traccion": "Delantera",
  "color": "Gris",
  "precio": 450000,
  "descripcion_adicional": "Amplio espacio de carga y asientos traseros abatibles para mayor comodidad",
  "fotos": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/2019_Citroen_Berlingo_Feel_Puretech_1.2_Front.jpg/800px-2019_Citroen_Berlingo_Feel_Puretech_1.2_Front.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": 20,
  "idusuario": 4,
  "tipo": "Camioneta",
  "marca": "Jeep",
  "modelo": "Wrangler",
  "version": "Sport",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Manual",
  "rodado": 17,
  "potencia": 285,
  "capacidad_carga": 500,
  "traccion": "4x4",
  "color": "Negro",
  "precio": 800000,
  "descripcion_adicional": "Potente motor V6 y sistema de tracción 4x4 para aventuras off-road",
  "fotos": [
    "https://http2.mlstatic.com/D_NQ_NP_855289-MLA53966637213_022023-O.webp",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": 21,
  "idusuario": 2,
  "tipo": "Camioneta",
  "marca": "Jeep",
  "modelo": "Grand Cherokee",
  "version": "Limited",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 18,
  "potencia": 295,
  "capacidad_carga": 500,
  "traccion": "4x4",
  "color": "Blanco",
  "precio": 1200000,
  "descripcion_adicional": "Equipado con asientos de cuero, sistema de sonido premium y techo panorámico",
  "fotos": [
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": 22,
  "idusuario": 4,
  "tipo": "Camioneta",
  "marca": "Jeep",
  "modelo": "Renegade",
  "version": "Sport",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Manual",
  "rodado": 16,
  "potencia": 180,
  "capacidad_carga": 400,
  "traccion": "Delantera",
  "color": "Azul",
  "precio": 600000,
  "descripcion_adicional": "Diseño moderno y juvenil, con sistema de sonido premium y pantalla táctil de 8 pulgadas",
  "fotos": [
    "https://acroadtrip.blob.core.windows.net/publicaciones-imagenes/Large/jeep/renegade/ar/RT_PU_c2ea779c584346b3821f27df53d10247.webp",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{ "id": 23, 
      "idusuario": 1, 
      "tipo": "Auto", 
      "marca": "Toyota", 
      "modelo": "Corolla", 
      "version": "LE", 
      "anio": 2021, 
      "kilometros": 0, 
      "transmision": "Automática", 
      "rodado": 16, 
      "potencia": 139, 
      "capacidad_carga": 400, 
      "traccion": "Delantera", 
      "color": "Blanco", 
      "precio": 350000, 
      "descripcion_adicional": "Nuevo modelo 2021 con pantalla táctil de 8 pulgadas y cámara de reversa", 
      "fotos": [ 
        "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg", 
        "https://ejemplo.com/foto2.jpg", 
        "https://ejemplo.com/foto3.jpg" 
      ] 
  }
];
  
module.exports = autos;