let autos = [ 
    { "id": "0", 
      "idusuario": "001", 
      "tipo": "Sedán", 
      "marca": "Toyota", 
      "modelo": "Corolla", 
      "version": "LE", 
      "anio": 2021, 
      "kilometros": 0, 
      "transmision": "Automática", 
      "rodado": 16, 
      "potencia": 139, 
      "capacidad_carga": 400, 
      "traccion": "Delantera", 
      "color": "Blanco", 
      "precio": 350000, 
      "descripcion_adicional": "Nuevo modelo 2021 con pantalla táctil de 8 pulgadas y cámara de reversa", 
      "fotos": [ 
        "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg", 
        "https://ejemplo.com/foto2.jpg", 
        "https://ejemplo.com/foto3.jpg" 
      ] 
    }, 
  { 
      "id": "1", 
      "idusuario": "002", 
      "tipo": "SUV", 
      "marca": "Nissan", 
      "modelo": "Kicks", 
      "version": "Advance", 
      "anio": 2020, 
      "kilometros": 20000, 
      "transmision": "Automática", 
      "rodado": 17, 
      "potencia": 118, 
      "capacidad_carga": 350, 
      "traccion": "Delantera", 
      "color": "Rojo", 
      "precio": 300000, 
      "descripcion_adicional": "Único dueño, servicios de agencia, en excelente estado", 
      "fotos": [ 
        "https://www.nissan-cdn.net/content/dam/Nissan/ar/vehicles/thumbnails/cars/Kicks_23_Advance_Plus.jpg.ximg.l_12_m.smart.jpg", 
        "https://ejemplo.com/foto5.jpg", 
        "https://ejemplo.com/foto6.jpg" 
      ] 
    }, 
    { 
      "id": "2", 
      "idusuario": "003", 
      "tipo": "Hatchback", 
      "marca": "Ford", 
      "modelo": "Fiesta", 
      "version": "SE", 
      "anio": 2019, 
      "kilometros": 40000, 
      "transmision": "Automática", 
      "rodado": 15, 
      "potencia": 120, 
      "capacidad_carga": 300, 
      "traccion": "Delantera", 
      "color": "Azul", 
      "precio": 250000, 
      "descripcion_adicional": "Excelente estado, servicios de agencia, único dueño", 
      "fotos": [ 
        "https://autotest.com.ar/wp-content/uploads/2021/09/Ford-Fiesta-SE-Plus-cola.jpg", 
        "https://ejemplo.com/foto8.jpg", 
        "https://ejemplo.com/foto9.jpg" 
      ] 
    }, 
    { 
      "id": "3", 
      "idusuario": "001",
      "tipo": "Pickup", 
      "marca": "Chevrolet", 
      "modelo": "Silverado", 
      "version": "LT", 
      "anio": 2020, 
      "kilometros": 5000, 
      "transmision": "Automática", 
      "rodado": 18, 
      "potencia": 355, 
      "capacidad_carga": 1000, 
      "traccion": "4x4", 
      "color": "Gris", 
      "precio": 700000, 
      "descripcion_adicional": "Prácticamente nueva, servicios de agencia, único dueño", 
      "fotos": [ 
        "https://www.chevrolet.com.uy/content/dam/chevrolet/south-america/uruguay/espanol/index/pick-ups/2021-silverado/01-images/galeria/exterior/chevrolet-silverado-camioneta-pick-up-exterior.jpg?imwidth=960", 
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": "4", 
      "idusuario": "003",
      "tipo": "Sedán", 
      "marca": "Honda", 
      "modelo": "Civic", 
      "version": "Touring", 
      "anio": 2021, 
      "kilometros": 0, 
      "transmision": "Automática", 
      "rodado": 17, 
      "potencia": 174, 
      "capacidad_carga": 350, 
      "traccion": "Delantera", 
      "color": "Negro", 
      "precio": 450000, 
      "descripcion_adicional": "Nuevo modelo 2021 con sistema de sonido premium y asientos de piel", 
      "fotos": [ 
        "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": "5", 
      "idusuario": "002",
      "tipo": "SUV", 
      "marca": "Jeep", 
      "modelo": "Compass", 
      "version": "Limited", 
      "anio": 2020, 
      "kilometros": 15000, 
      "transmision": "Automática", 
      "rodado": 18, 
      "potencia": 180, 
      "capacidad_carga": 400, 
      "traccion": "4x4", 
      "color": "Blanco", 
      "precio": 550000, 
      "descripcion_adicional": "Servicios de agencia, en excelente estado", 
      "fotos": [ 
        "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": "6", 
      "idusuario": "001",
      "tipo": "Deportivo", 
      "marca": "Mazda", 
      "modelo": "MX-5", 
      "version": "RF", 
      "anio": 2021, 
      "kilometros": 0, 
      "transmision": "Manual", 
      "rodado": 17, 
      "potencia": 181, 
      "capacidad_carga": 200, 
      "traccion": "Trasera", 
      "color": "Rojo", 
      "precio": 600000, 
      "descripcion_adicional": "Nuevo modelo 2021, descapotable, asientos deportivos de piel", 
      "fotos": [ 
        "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": "7", 
      "idusuario": "003",
      "tipo": "Sedán", 
      "marca": "Volkswagen", 
      "modelo": "Vento", 
      "version": "Highline", 
      "anio": 2018, 
      "kilometros": 60000, 
      "transmision": "Automática", 
      "rodado": 15, 
      "potencia": 110, 
      "capacidad_carga": 350, 
      "traccion": "Delantera", 
      "color": "Gris", 
      "precio": 200000, 
      "descripcion_adicional": "Único dueño, servicios de agencia, en buen estado", 
      "fotos": [ 
        "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": "8", 
      "idusuario": "002",
      "tipo": "SUV", 
      "marca": "Renault", 
      "modelo": "Captur", 
      "version": "Zen", 
      "anio": 2019, 
      "kilometros": 35000, 
      "transmision": "Automática", 
      "rodado": 17, 
      "potencia": 118, 
      "capacidad_carga": 350, 
      "traccion": "Delantera", 
      "color": "Azul", 
      "precio": 280000, 
      "descripcion_adicional": "Servicios de agencia, en buen estado", 
      "fotos": [ 
        "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": "9", 
      "idusuario": "001",
      "tipo": "Pickup", 
      "marca": "Ford", 
      "modelo": "Ranger", 
      "version": "XLT", 
      "anio": 2020, 
      "kilometros": 10000, 
      "transmision": "Automática", 
      "rodado": 18, 
      "potencia": 270, 
      "capacidad_carga": 1000, 
      "traccion": "4x4", 
      "color": "Negro", 
      "precio": 750000, 
      "descripcion_adicional": "Servicios de agencia, en excelente estado", 
      "fotos": [ 
        "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": "10", 
      "idusuario": "003",
      "tipo": "Sedán", 
      "marca": "Chevrolet", 
      "modelo": "Cruze", 
      "version": "LT", 
      "anio": 2017, 
      "kilometros": 80000, 
      "transmision": "Automática", 
      "rodado": 16, 
      "potencia": 153, 
      "capacidad_carga": 350, 
      "traccion": "Delantera", 
      "color": "Gris", 
      "precio": 180000, 
      "descripcion_adicional": "Único dueño, en buen estado", 
      "fotos": [ 
        "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
    }, 
    { 
      "id": "11", 
      "idusuario": "002",
      "tipo": "SUV", 
      "marca": "Toyota", 
      "modelo": "Rav4", 
      "version": "XLE", 
      "anio": 2019, 
      "kilometros": 30000, 
      "transmision": "Automática", 
      "rodado": 17, 
      "potencia": 203, 
      "capacidad_carga": 400, 
      "traccion": "4x4", 
      "color": "Blanco", 
      "precio": 500000, 
      "descripcion_adicional": "Servicios de agencia, en excelente estado", 
      "fotos": [ 
        "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
        "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg" 
      ] 
  },
  {
  "id": "12",
  "idusuario": "001",
  "tipo": "Coupé",
  "marca": "Volkswagen",
  "modelo": "Arteon",
  "version": "R-Line",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 20,
  "potencia": 268,
  "capacidad_carga": 400,
  "traccion": "4x4",
  "color": "Blanco",
  "precio": 800000,
  "descripcion_adicional": "Nuevo modelo 2021 con sistema de cámara 360 y asientos de cuero Nappa",
  "fotos": [
    "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
  }, {
  "id": "13",
  "idusuario": "002",
  "tipo": "SUV",
  "marca": "Volkswagen",
  "modelo": "Tiguan",
  "version": "R-Line",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 20,
  "potencia": 184,
  "capacidad_carga": 500,
  "traccion": "4x4",
  "color": "Azul",
  "precio": 700000,
  "descripcion_adicional": "Nuevo modelo 2021 con sistema de sonido Fender y techo panorámico corredizo",
  "fotos": [
    "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": "14",
  "idusuario": "003",
  "tipo": "Sedán",
  "marca": "Volkswagen",
  "modelo": "Passat",
  "version": "R-Line",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 19,
  "potencia": 276,
  "capacidad_carga": 400,
  "traccion": "Delantera",
  "color": "Gris",
  "precio": 600000,
  "descripcion_adicional": "Nuevo modelo 2021 con sistema de asistencia de frenado de emergencia y control de crucero adaptativo",
  "fotos": [
    "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
  },
  {
  "id": "15",
  "idusuario": "003",
  "tipo": "Hatchback",
  "marca": "Volkswagen",
  "modelo": "Golf",
  "version": "GTI",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 18,
  "potencia": 241,
  "capacidad_carga": 400,
  "traccion": "Delantera",
  "color": "Negro",
  "precio": 500000,
  "descripcion_adicional": "Nuevo modelo 2021 con techo corredizo panorámico y sistema de navegación",
  "fotos": [
    "https://blog.karvi.com.ar/wp-content/uploads/2021/02/corolla1.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": "16",
  "idusuario": "002",
  "tipo": "Sedán",
  "marca": "Volkswagen",
  "modelo": "Jetta",
  "version": "GLI",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 18,
  "potencia": 228,
  "capacidad_carga": 400,
  "traccion": "Delantera",
  "color": "Rojo",
  "precio": 450000,
  "descripcion_adicional": "Nuevo modelo 2021 con sistema de sonido premium y asientos deportivos",
  "fotos": [
    "https://cdn.motor1.com/images/mgl/L3Yxrm/s3/volkswagen-jetta-gli-2022.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": "17",
  "idusuario": "001",
  "tipo": "Hatchback",
  "marca": "Citroen",
  "modelo": "C3",
  "version": "Feel",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Manual",
  "rodado": 16,
  "potencia": 82,
  "capacidad_carga": 300,
  "traccion": "Delantera",
  "color": "Rojo",
  "precio": 300000,
  "descripcion_adicional": "Nuevo modelo 2021 con pantalla táctil de 7 pulgadas y cámara de reversa",
  "fotos": [
    "https://resizer.glanacion.com/resizer/VF2xQu7-PgIE6h3S9-4U-RSluTY=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/4FYT7ABYINEGZGUA5TGGBXWBGA.jpeg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": "18",
  "idusuario": "002",
  "tipo": "SUV",
  "marca": "Citroen",
  "modelo": "C4 Cactus",
  "version": "Feel",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 17,
  "potencia": 118,
  "capacidad_carga": 500,
  "traccion": "Delantera",
  "color": "Blanco",
  "precio": 400000,
  "descripcion_adicional": "Incluye techo panorámico y sistema de navegación GPS",
  "fotos": [
    "https://automobileslyon.com.ar/wp-content/uploads/2020/12/3-1-898x558.jpg?x10793",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": "19",
  "idusuario": "004",
  "tipo": "Furgoneta",
  "marca": "Citroen",
  "modelo": "Berlingo",
  "version": "Feel",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Manual",
  "rodado": 15,
  "potencia": 110,
  "capacidad_carga": 800,
  "traccion": "Delantera",
  "color": "Gris",
  "precio": 450000,
  "descripcion_adicional": "Amplio espacio de carga y asientos traseros abatibles para mayor comodidad",
  "fotos": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/2019_Citroen_Berlingo_Feel_Puretech_1.2_Front.jpg/800px-2019_Citroen_Berlingo_Feel_Puretech_1.2_Front.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": "20",
  "idusuario": "004",
  "tipo": "SUV",
  "marca": "Jeep",
  "modelo": "Wrangler",
  "version": "Sport",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Manual",
  "rodado": 17,
  "potencia": 285,
  "capacidad_carga": 500,
  "traccion": "4x4",
  "color": "Negro",
  "precio": 800000,
  "descripcion_adicional": "Potente motor V6 y sistema de tracción 4x4 para aventuras off-road",
  "fotos": [
    "https://http2.mlstatic.com/D_NQ_NP_855289-MLA53966637213_022023-O.webp",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": "21",
  "idusuario": "002",
  "tipo": "SUV",
  "marca": "Jeep",
  "modelo": "Grand Cherokee",
  "version": "Limited",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Automática",
  "rodado": 18,
  "potencia": 295,
  "capacidad_carga": 500,
  "traccion": "4x4",
  "color": "Blanco",
  "precio": 1200000,
  "descripcion_adicional": "Equipado con asientos de cuero, sistema de sonido premium y techo panorámico",
  "fotos": [
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
},{"id": "22",
  "idusuario": "004",
  "tipo": "SUV",
  "marca": "Jeep",
  "modelo": "Renegade",
  "version": "Sport",
  "anio": 2021,
  "kilometros": 0,
  "transmision": "Manual",
  "rodado": 16,
  "potencia": 180,
  "capacidad_carga": 400,
  "traccion": "Delantera",
  "color": "Azul",
  "precio": 600000,
  "descripcion_adicional": "Diseño moderno y juvenil, con sistema de sonido premium y pantalla táctil de 8 pulgadas",
  "fotos": [
    "https://acroadtrip.blob.core.windows.net/publicaciones-imagenes/Large/jeep/renegade/ar/RT_PU_c2ea779c584346b3821f27df53d10247.webp",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg",
    "https://noticias.coches.com/wp-content/uploads/2014/07/jeep_grand-cherokee-limited-2013_r10.jpg"
  ]
}
];
  
module.exports = autos;